import { Component, computed, inject, input } from '@angular/core';
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser';
import { barkastGlassSVG, type GlassSpec } from './glass-svg';

/**
 * Renders a Barkast cocktail glass as inline SVG from a {@link GlassSpec}. The SVG string is
 * generated by our own code (no user input), so it is trusted and bypasses Angular sanitising —
 * which would otherwise strip the gradients and transforms the drawing relies on.
 */
@Component({
  selector: 'app-glass-art',
  template: `<span class="wrap" [innerHTML]="html()"></span>`,
  styles: `
    :host {
      display: block;
      width: 100%;
      height: 100%;
    }
    .wrap {
      display: block;
      width: 100%;
      height: 100%;
    }
  `,
})
export class GlassArt {
  private readonly sanitizer = inject(DomSanitizer);
  readonly spec = input.required<GlassSpec>();

  protected readonly html = computed<SafeHtml>(() =>
    this.sanitizer.bypassSecurityTrustHtml(barkastGlassSVG(this.spec())),
  );
}
