import type { Cocktail, Ingredient } from '@cocktailapp/shared';
import catalogJson from '../../assets/catalog.json';

export interface CatalogData {
  version: string;
  generatedFrom?: string;
  counts: { ingredients: number; cocktails: number };
  ingredients: Ingredient[];
  cocktails: Cocktail[];
}

/**
 * The offline catalog bundled with the app, generated by scripts/build-catalog.mjs
 * from iba-cocktails-seed.json. This is the app's local-first data source: it works
 * with no network and no account. A future step adds refresh-from-/api/catalog.
 */
export const catalog = catalogJson as unknown as CatalogData;
