import type { Cocktail, Ingredient } from '@cocktailapp/shared';
import { create } from 'zustand';
import catalogJson from '../../assets/catalog.json';
import { track } from './analytics';
import { fetchCatalog } from './api';
import { hasBackend } from './config';
import { kv } from './storage';

export interface CatalogData {
  version: string;
  generatedFrom?: string;
  counts: { ingredients: number; cocktails: number };
  ingredients: Ingredient[];
  cocktails: Cocktail[];
}

/**
 * The offline catalog bundled with the app, generated by scripts/build-catalog.mjs from
 * iba-cocktails-seed.json. This is the local-first floor: the app works with no network and no
 * account off this bundle alone.
 */
export const bundledCatalog = catalogJson as unknown as CatalogData;

const DATA_KEY = 'barkast.catalog.data';
const ETAG_KEY = 'barkast.catalog.etag';

/**
 * The active catalog. Starts from the bundled snapshot (instant, offline), then:
 *   - {@link loadCachedCatalog} swaps in a previously refreshed copy from storage on launch;
 *   - {@link refreshCatalog} conditionally pulls `/api/catalog` (ETag/304) and caches any update.
 * Every read (`computeMakeable`, lists, detail) uses `useCatalog().catalog`, so a refresh flows to
 * the whole UI. `computeMakeable` still runs on-device — the network only supplies fresher content.
 */
interface CatalogState {
  catalog: CatalogData;
  refreshing: boolean;
  setCatalog: (catalog: CatalogData) => void;
  setRefreshing: (refreshing: boolean) => void;
}

export const useCatalog = create<CatalogState>((set) => ({
  catalog: bundledCatalog,
  refreshing: false,
  setCatalog: (catalog) => set({ catalog }),
  setRefreshing: (refreshing) => set({ refreshing }),
}));

/** Load a previously cached (refreshed) catalog from storage. Falls back to the bundle silently. */
export async function loadCachedCatalog(): Promise<void> {
  try {
    const raw = await kv.get(DATA_KEY);
    if (!raw) return;
    const cached = JSON.parse(raw) as CatalogData;
    if (cached?.ingredients?.length && cached?.cocktails?.length) {
      useCatalog.getState().setCatalog(cached);
    }
  } catch {
    /* corrupt cache — keep the bundle */
  }
}

/**
 * Conditionally refresh from the backend. No-op (and no error) when no backend is configured or
 * the device is offline — the bundled/cached catalog keeps serving. On a 200 we adopt + cache the
 * new content; on a 304 we keep what we have.
 */
export async function refreshCatalog(): Promise<void> {
  if (!hasBackend) return;
  const store = useCatalog.getState();
  store.setRefreshing(true);
  try {
    const etag = (await kv.get(ETAG_KEY)) ?? undefined;
    const result = await fetchCatalog(etag);
    if (!result.notModified) {
      const next: CatalogData = {
        version: result.catalog.version,
        generatedFrom: result.catalog.generatedFrom,
        counts: result.catalog.counts,
        ingredients: result.catalog.ingredients,
        cocktails: result.catalog.cocktails,
      };
      store.setCatalog(next);
      await kv.set(DATA_KEY, JSON.stringify(next));
      if (result.etag) await kv.set(ETAG_KEY, result.etag);
      track({ type: 'catalog_refresh' });
    }
  } catch {
    /* offline or server down — local-first, so ignore */
  } finally {
    store.setRefreshing(false);
  }
}
