/**
 * Curated seed dataset for CocktailApp.
 *
 * - `ingredients`: the catalog. `isStaple` items are the "je hebt dit vast al in huis"
 *   presets shown (pre-checked) in the first step of the bar wizard.
 * - `cocktails`: reference ingredients by name; the seeder resolves each to its catalog
 *   id. Pure garnish (twists, cherries, salt rims) lives in the `garnish` string, so it
 *   never counts against "wat kan ik maken". Amounts use cl (NL convention).
 */

export const ingredients = [
  // --- Sterke drank ---
  { name: 'Gin', category: 'spirit' },
  { name: 'Wodka', category: 'spirit' },
  { name: 'Witte rum', category: 'spirit' },
  { name: 'Donkere rum', category: 'spirit' },
  { name: 'Tequila blanco', category: 'spirit' },
  { name: 'Bourbon whiskey', category: 'spirit' },
  { name: 'Rye whiskey', category: 'spirit' },
  { name: 'Cognac', category: 'spirit' },
  { name: 'Cachaça', category: 'spirit' },

  // --- Likeuren & vermout ---
  { name: 'Campari', category: 'liqueur' },
  { name: 'Aperol', category: 'liqueur' },
  { name: 'Rode vermout', category: 'liqueur' },
  { name: 'Droge vermout', category: 'liqueur' },
  { name: 'Triple sec', category: 'liqueur' },
  { name: 'Koffielikeur', category: 'liqueur' },
  { name: 'Crème de cassis', category: 'liqueur' },

  // --- Mixers & bubbels ---
  { name: 'Tonic', category: 'mixer', isStaple: true },
  { name: 'Cola', category: 'mixer', isStaple: true },
  { name: 'Ginger beer', category: 'mixer' },
  { name: 'Sodawater', category: 'mixer', isStaple: true },
  { name: 'Prosecco', category: 'mixer' },

  // --- Sappen ---
  { name: 'Citroensap', category: 'juice', isStaple: true },
  { name: 'Limoensap', category: 'juice', isStaple: true },
  { name: 'Sinaasappelsap', category: 'juice', isStaple: true },
  { name: 'Cranberrysap', category: 'juice' },
  { name: 'Ananassap', category: 'juice' },
  { name: 'Tomatensap', category: 'juice' },
  { name: 'Grapefruitsap', category: 'juice' },

  // --- Siropen ---
  { name: 'Suikersiroop', category: 'syrup', isStaple: true },
  { name: 'Grenadine', category: 'syrup' },
  { name: 'Orgeat (amandelsiroop)', category: 'syrup' },
  { name: 'Framboossiroop', category: 'syrup' },

  // --- Bitters ---
  { name: 'Angostura bitters', category: 'bitters' },
  { name: 'Orange bitters', category: 'bitters' },

  // --- Verse producten (structureel) ---
  { name: 'Munt', category: 'garnish' },
  { name: 'Limoen', category: 'garnish' },
  { name: 'Citroen', category: 'garnish' },

  // --- Overig ---
  { name: 'IJs', category: 'other', isStaple: true },
  { name: 'Suiker', category: 'other', isStaple: true },
  { name: 'Eiwit', category: 'other' },
  { name: 'Espresso', category: 'other' },
  { name: 'Worcestersaus', category: 'other' },
  { name: 'Tabasco', category: 'other' },
  { name: 'Kokosroom', category: 'other' },
];

// Shorthand: [name, amount, unit, { optional, note }?]
const I = (name, amount, unit, extra = {}) => ({ name, amount, unit, ...extra });

export const cocktails = [
  {
    name: 'Negroni',
    description: 'De perfect gebalanceerde Italiaanse aperitief: bitter, kruidig en tijdloos.',
    glass: 'rocks',
    method: 'stirred',
    difficulty: 'easy',
    garnish: 'Schijfje sinaasappel',
    tags: ['bitter', 'aperitief', 'klassiek', 'sterk'],
    ingredients: [I('Gin', 3, 'cl'), I('Campari', 3, 'cl'), I('Rode vermout', 3, 'cl'), I('IJs', 4, 'cube')],
    instructions: [
      'Vul een rocksglas met ijs.',
      'Schenk gin, Campari en rode vermout in het glas.',
      'Roer 20 seconden tot goed gekoeld.',
      'Garneer met een schijfje sinaasappel.',
    ],
  },
  {
    name: 'Margarita',
    description: 'Fris en pittig met tequila, limoen en een zoutrand.',
    glass: 'coupe',
    method: 'shaken',
    difficulty: 'easy',
    garnish: 'Zoutrand en schijfje limoen',
    tags: ['fris', 'citrus', 'klassiek'],
    ingredients: [I('Tequila blanco', 5, 'cl'), I('Triple sec', 2, 'cl'), I('Limoensap', 2, 'cl'), I('IJs', 5, 'cube')],
    instructions: [
      'Maak een zoutrand op het glas met een partje limoen en zout.',
      'Doe tequila, triple sec en limoensap met ijs in een shaker.',
      'Shake 15 seconden.',
      'Zeef in het glas en garneer met limoen.',
    ],
  },
  {
    name: 'Daiquiri',
    description: 'Drie ingrediënten in perfecte harmonie — rum, limoen en suiker.',
    glass: 'coupe',
    method: 'shaken',
    difficulty: 'easy',
    garnish: 'Schijfje limoen',
    tags: ['fris', 'citrus', 'klassiek'],
    ingredients: [I('Witte rum', 6, 'cl'), I('Limoensap', 2.5, 'cl'), I('Suikersiroop', 1.5, 'cl'), I('IJs', 5, 'cube')],
    instructions: [
      'Doe alle ingrediënten met ijs in een shaker.',
      'Shake stevig 15 seconden.',
      'Dubbel zeven in een gekoelde coupe.',
      'Garneer met een schijfje limoen.',
    ],
  },
  {
    name: 'Mojito',
    description: 'Cubaanse verfrissing met munt, limoen en bruisend afgetopt.',
    glass: 'collins',
    method: 'muddled',
    difficulty: 'medium',
    garnish: 'Munttakje en schijfje limoen',
    tags: ['fris', 'munt', 'zomer', 'lang'],
    ingredients: [
      I('Witte rum', 6, 'cl'),
      I('Limoensap', 3, 'cl'),
      I('Suiker', 2, 'teaspoon'),
      I('Munt', 8, 'piece'),
      I('Sodawater', 6, 'cl', { note: 'om af te toppen' }),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Muddle de munt zacht met suiker en limoensap in een longdrinkglas.',
      'Voeg rum en gemalen ijs toe.',
      'Roer en top af met sodawater.',
      'Garneer royaal met munt.',
    ],
  },
  {
    name: 'Old Fashioned',
    description: 'De oervorm van de cocktail: whiskey, suiker en bitters.',
    glass: 'rocks',
    method: 'stirred',
    difficulty: 'medium',
    garnish: 'Sinaasappelschil',
    tags: ['sterk', 'klassiek', 'whiskey'],
    ingredients: [
      I('Bourbon whiskey', 6, 'cl'),
      I('Suikersiroop', 1, 'cl'),
      I('Angostura bitters', 2, 'dash'),
      I('IJs', 3, 'cube'),
    ],
    instructions: [
      'Doe suikersiroop en bitters in een rocksglas.',
      'Voeg de bourbon en een groot ijsblok toe.',
      'Roer 30 seconden tot gekoeld en verdund.',
      'Wring een sinaasappelschil boven het glas uit en leg erin.',
    ],
  },
  {
    name: 'Manhattan',
    description: 'Elegant en krachtig: rye, zoete vermout en bitters.',
    glass: 'nick_and_nora',
    method: 'stirred',
    difficulty: 'medium',
    garnish: 'Cocktailkers',
    tags: ['sterk', 'klassiek', 'whiskey'],
    ingredients: [
      I('Rye whiskey', 6, 'cl'),
      I('Rode vermout', 3, 'cl'),
      I('Angostura bitters', 2, 'dash'),
      I('IJs', 5, 'cube'),
    ],
    instructions: [
      'Roer whiskey, vermout en bitters met ijs in een mengglas.',
      'Roer 25 seconden tot goed gekoeld.',
      'Zeef in een gekoelde coupe of Nick & Nora.',
      'Garneer met een cocktailkers.',
    ],
  },
  {
    name: 'Dry Martini',
    description: 'Zuiver en ijskoud — het icoon onder de cocktails.',
    glass: 'martini',
    method: 'stirred',
    difficulty: 'medium',
    garnish: 'Olijf of citroenschil',
    tags: ['sterk', 'klassiek', 'droog'],
    ingredients: [
      I('Gin', 6, 'cl'),
      I('Droge vermout', 1, 'cl'),
      I('Orange bitters', 1, 'dash', { optional: true }),
      I('IJs', 5, 'cube'),
    ],
    instructions: [
      'Roer gin en vermout met veel ijs in een mengglas.',
      'Roer 30 seconden tot ijskoud.',
      'Zeef in een gekoeld martiniglas.',
      'Garneer met een olijf of een citroenschil.',
    ],
  },
  {
    name: 'Cosmopolitan',
    description: 'Stijlvol en fruitig met wodka, cranberry en limoen.',
    glass: 'martini',
    method: 'shaken',
    difficulty: 'easy',
    garnish: 'Sinaasappelschil',
    tags: ['fruitig', 'citrus', 'modern'],
    ingredients: [
      I('Wodka', 4, 'cl'),
      I('Triple sec', 1.5, 'cl'),
      I('Cranberrysap', 3, 'cl'),
      I('Limoensap', 1.5, 'cl'),
      I('IJs', 5, 'cube'),
    ],
    instructions: [
      'Doe alle ingrediënten met ijs in een shaker.',
      'Shake 15 seconden.',
      'Zeef in een gekoeld martiniglas.',
      'Garneer met een sinaasappelschil.',
    ],
  },
  {
    name: 'Whiskey Sour',
    description: 'Zacht schuimend, met de perfecte balans tussen zuur en zoet.',
    glass: 'rocks',
    method: 'shaken',
    difficulty: 'medium',
    garnish: 'Cocktailkers en schijfje citroen',
    tags: ['citrus', 'klassiek', 'whiskey'],
    ingredients: [
      I('Bourbon whiskey', 5, 'cl'),
      I('Citroensap', 2.5, 'cl'),
      I('Suikersiroop', 1.5, 'cl'),
      I('Eiwit', 1, 'piece', { optional: true, note: 'voor schuim' }),
      I('Angostura bitters', 2, 'dash', { optional: true }),
      I('IJs', 5, 'cube'),
    ],
    instructions: [
      'Doe bourbon, citroensap, siroop en eiwit zonder ijs in een shaker (dry shake).',
      'Voeg ijs toe en shake nogmaals goed.',
      'Zeef in een rocksglas met vers ijs.',
      'Druppel bitters op het schuim en garneer.',
    ],
  },
  {
    name: 'Espresso Martini',
    description: 'Wakker én ontspannen: wodka, koffielikeur en verse espresso.',
    glass: 'martini',
    method: 'shaken',
    difficulty: 'medium',
    garnish: 'Drie koffiebonen',
    tags: ['koffie', 'modern', 'dessert'],
    ingredients: [
      I('Wodka', 4, 'cl'),
      I('Koffielikeur', 2, 'cl'),
      I('Espresso', 3, 'cl', { note: 'vers en heet' }),
      I('Suikersiroop', 1, 'cl'),
      I('IJs', 5, 'cube'),
    ],
    instructions: [
      'Doe alle ingrediënten met ijs in een shaker.',
      'Shake hard 20 seconden voor een mooie schuimlaag.',
      'Dubbel zeven in een gekoeld glas.',
      'Garneer met drie koffiebonen.',
    ],
  },
  {
    name: 'Aperol Spritz',
    description: 'De ultieme zonnige aperitief: licht bitter en bruisend.',
    glass: 'wine',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Schijfje sinaasappel',
    tags: ['bitter', 'aperitief', 'bubbels', 'zomer'],
    ingredients: [
      I('Aperol', 6, 'cl'),
      I('Prosecco', 9, 'cl'),
      I('Sodawater', 3, 'cl'),
      I('IJs', 5, 'cube'),
    ],
    instructions: [
      'Vul een wijnglas met ijs.',
      'Schenk prosecco, dan Aperol, dan een scheut soda.',
      'Roer één keer voorzichtig.',
      'Garneer met een schijfje sinaasappel.',
    ],
  },
  {
    name: 'Gin-Tonic',
    description: 'Simpel, fris en eindeloos variabel — de klassieke longdrink.',
    glass: 'highball',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Schijfje limoen of komkommer',
    tags: ['fris', 'bubbels', 'lang', 'makkelijk'],
    ingredients: [I('Gin', 5, 'cl'), I('Tonic', 15, 'cl'), I('IJs', 6, 'cube')],
    instructions: [
      'Vul een longdrinkglas royaal met ijs.',
      'Schenk de gin erover.',
      'Top af met koude tonic.',
      'Garneer met limoen of komkommer.',
    ],
  },
  {
    name: 'Moscow Mule',
    description: 'Pittige gember, wodka en limoen — traditioneel in een koperen mok.',
    glass: 'mug',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Schijfje limoen en munt',
    tags: ['fris', 'gember', 'lang'],
    ingredients: [
      I('Wodka', 5, 'cl'),
      I('Limoensap', 1.5, 'cl'),
      I('Ginger beer', 12, 'cl'),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Vul een mok of longdrinkglas met ijs.',
      'Schenk wodka en limoensap erin.',
      'Top af met ginger beer.',
      'Roer kort en garneer met limoen en munt.',
    ],
  },
  {
    name: 'Cuba Libre',
    description: 'Rum en cola met een frisse scheut limoen.',
    glass: 'highball',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Partje limoen',
    tags: ['fris', 'lang', 'makkelijk'],
    ingredients: [
      I('Witte rum', 5, 'cl'),
      I('Limoensap', 1, 'cl'),
      I('Cola', 12, 'cl'),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Vul een longdrinkglas met ijs.',
      'Schenk rum en limoensap erin.',
      'Top af met cola.',
      'Knijp een partje limoen erboven uit.',
    ],
  },
  {
    name: 'Mai Tai',
    description: 'Tropische tiki-klassieker met rum, amandel en citrus.',
    glass: 'rocks',
    method: 'shaken',
    difficulty: 'medium',
    garnish: 'Munttakje en limoen',
    tags: ['tropisch', 'tiki', 'fruitig'],
    ingredients: [
      I('Donkere rum', 6, 'cl'),
      I('Triple sec', 1.5, 'cl'),
      I('Limoensap', 2, 'cl'),
      I('Orgeat (amandelsiroop)', 1.5, 'cl'),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Doe alle ingrediënten met ijs in een shaker.',
      'Shake 15 seconden.',
      'Schenk ongezeefd in een glas met gemalen ijs.',
      'Garneer met munt en limoen.',
    ],
  },
  {
    name: 'Piña Colada',
    description: 'Romig-tropisch met rum, ananas en kokos.',
    glass: 'hurricane',
    method: 'blended',
    difficulty: 'easy',
    garnish: 'Ananaspunt',
    tags: ['tropisch', 'romig', 'zomer'],
    ingredients: [
      I('Witte rum', 5, 'cl'),
      I('Ananassap', 9, 'cl'),
      I('Kokosroom', 3, 'cl'),
      I('IJs', 8, 'cube'),
    ],
    instructions: [
      'Doe alle ingrediënten met ijs in een blender.',
      'Blend tot een gladde, romige textuur.',
      'Schenk in een hurricaneglas.',
      'Garneer met een ananaspunt.',
    ],
  },
  {
    name: 'Caipirinha',
    description: 'Braziliës nationale drankje: cachaça, limoen en suiker.',
    glass: 'rocks',
    method: 'muddled',
    difficulty: 'easy',
    garnish: 'Partje limoen',
    tags: ['fris', 'citrus', 'zomer'],
    ingredients: [
      I('Cachaça', 6, 'cl'),
      I('Limoen', 1, 'piece'),
      I('Suiker', 2, 'teaspoon'),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Snijd de limoen in partjes en muddle met suiker in een rocksglas.',
      'Voeg gemalen ijs toe.',
      'Schenk de cachaça erover.',
      'Roer goed door.',
    ],
  },
  {
    name: 'Tom Collins',
    description: 'Verfrissende gin-sour, lang en bruisend.',
    glass: 'collins',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Schijfje citroen en cocktailkers',
    tags: ['fris', 'citrus', 'bubbels', 'lang'],
    ingredients: [
      I('Gin', 5, 'cl'),
      I('Citroensap', 3, 'cl'),
      I('Suikersiroop', 1.5, 'cl'),
      I('Sodawater', 6, 'cl'),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Schud gin, citroensap en siroop met ijs.',
      'Zeef in een longdrinkglas met vers ijs.',
      'Top af met sodawater.',
      'Garneer met citroen en een kers.',
    ],
  },
  {
    name: 'Mimosa',
    description: 'Brunch-klassieker: prosecco met vers sinaasappelsap.',
    glass: 'flute',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Sinaasappelschil',
    tags: ['bubbels', 'brunch', 'fruitig', 'makkelijk'],
    ingredients: [I('Prosecco', 8, 'cl'), I('Sinaasappelsap', 8, 'cl')],
    instructions: [
      'Schenk het sinaasappelsap in een gekoelde flûte.',
      'Vul rustig aan met prosecco.',
      'Roer één keer heel voorzichtig.',
    ],
  },
  {
    name: 'Bloody Mary',
    description: 'Hartig en kruidig — het beroemde brunch-medicijn.',
    glass: 'highball',
    method: 'build',
    difficulty: 'medium',
    garnish: 'Selderijstengel en citroen',
    tags: ['hartig', 'kruidig', 'brunch'],
    ingredients: [
      I('Wodka', 5, 'cl'),
      I('Tomatensap', 12, 'cl'),
      I('Citroensap', 1.5, 'cl'),
      I('Worcestersaus', 3, 'dash'),
      I('Tabasco', 3, 'dash'),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Doe alle ingrediënten met ijs in een glas.',
      'Rol de drank over tussen twee glazen om te mengen.',
      'Breng op smaak met peper en zout.',
      'Garneer met selderij en citroen.',
    ],
  },
  {
    name: 'Negroni Sbagliato',
    description: 'De bubbelende "vergissing": Negroni met prosecco in plaats van gin.',
    glass: 'rocks',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Schijfje sinaasappel',
    tags: ['bitter', 'aperitief', 'bubbels'],
    ingredients: [
      I('Campari', 3, 'cl'),
      I('Rode vermout', 3, 'cl'),
      I('Prosecco', 3, 'cl'),
      I('IJs', 4, 'cube'),
    ],
    instructions: [
      'Vul een glas met ijs.',
      'Schenk Campari en rode vermout erin.',
      'Top af met prosecco.',
      'Garneer met een schijfje sinaasappel.',
    ],
  },
  {
    name: 'Paloma',
    description: 'Mexicaanse dorstlesser met tequila en grapefruit.',
    glass: 'highball',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Partje limoen en zoutrand',
    tags: ['fris', 'citrus', 'lang'],
    ingredients: [
      I('Tequila blanco', 5, 'cl'),
      I('Grapefruitsap', 6, 'cl'),
      I('Limoensap', 1.5, 'cl'),
      I('Sodawater', 6, 'cl'),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Vul een longdrinkglas met ijs.',
      'Schenk tequila, grapefruitsap en limoensap erin.',
      'Top af met sodawater en roer kort.',
      'Garneer met limoen; optioneel een zoutrand.',
    ],
  },
  {
    name: 'French 75',
    description: 'Elegant en feestelijk: gin, citroen en champagne.',
    glass: 'flute',
    method: 'shaken',
    difficulty: 'medium',
    garnish: 'Citroenschil',
    tags: ['bubbels', 'citrus', 'feest', 'klassiek'],
    ingredients: [
      I('Gin', 3, 'cl'),
      I('Citroensap', 1.5, 'cl'),
      I('Suikersiroop', 1, 'cl'),
      I('Prosecco', 6, 'cl', { note: 'of champagne' }),
      I('IJs', 5, 'cube'),
    ],
    instructions: [
      'Shake gin, citroensap en siroop met ijs.',
      'Zeef in een gekoelde flûte.',
      'Top af met prosecco of champagne.',
      'Garneer met een lange citroenschil.',
    ],
  },
  {
    name: 'Sidecar',
    description: 'Verfijnde cognac-sour met een suikerrand.',
    glass: 'coupe',
    method: 'shaken',
    difficulty: 'medium',
    garnish: 'Suikerrand en sinaasappelschil',
    tags: ['citrus', 'klassiek', 'sterk'],
    ingredients: [
      I('Cognac', 5, 'cl'),
      I('Triple sec', 2, 'cl'),
      I('Citroensap', 2, 'cl'),
      I('IJs', 5, 'cube'),
    ],
    instructions: [
      'Maak eventueel een suikerrand op de coupe.',
      'Shake cognac, triple sec en citroensap met ijs.',
      'Dubbel zeven in de coupe.',
      'Garneer met een sinaasappelschil.',
    ],
  },
  {
    name: 'Mint Julep',
    description: 'Zuidelijke klassieker met bourbon en veel verse munt.',
    glass: 'mug',
    method: 'muddled',
    difficulty: 'medium',
    garnish: 'Grote bos munt',
    tags: ['munt', 'whiskey', 'zomer'],
    ingredients: [
      I('Bourbon whiskey', 6, 'cl'),
      I('Suiker', 1, 'teaspoon'),
      I('Munt', 10, 'piece'),
      I('IJs', 8, 'cube'),
    ],
    instructions: [
      'Muddle munt zacht met suiker in een mok.',
      'Vul met gemalen ijs.',
      'Schenk de bourbon erover en roer tot het glas beslaat.',
      'Garneer met een grote bos munt.',
    ],
  },
  {
    name: "Dark 'n' Stormy",
    description: 'Donkere rum die door de gingerbeer "stormt".',
    glass: 'highball',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Partje limoen',
    tags: ['gember', 'lang', 'fris'],
    ingredients: [
      I('Ginger beer', 12, 'cl'),
      I('Donkere rum', 6, 'cl', { note: 'als laatste, laten drijven' }),
      I('Limoensap', 1, 'cl'),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Vul een longdrinkglas met ijs.',
      'Schenk ginger beer en limoensap erin.',
      'Laat de donkere rum er voorzichtig bovenop drijven.',
      'Garneer met een partje limoen.',
    ],
  },
  {
    name: 'Screwdriver',
    description: 'Kan niet simpeler: wodka en sinaasappelsap.',
    glass: 'highball',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Schijfje sinaasappel',
    tags: ['fruitig', 'lang', 'makkelijk'],
    ingredients: [I('Wodka', 5, 'cl'), I('Sinaasappelsap', 12, 'cl'), I('IJs', 6, 'cube')],
    instructions: [
      'Vul een longdrinkglas met ijs.',
      'Schenk de wodka erin.',
      'Top af met sinaasappelsap en roer kort.',
    ],
  },
  {
    name: 'Tequila Sunrise',
    description: 'Zonsopgang in een glas dankzij een laagje grenadine.',
    glass: 'highball',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Schijfje sinaasappel en kers',
    tags: ['fruitig', 'lang', 'kleurrijk'],
    ingredients: [
      I('Tequila blanco', 5, 'cl'),
      I('Sinaasappelsap', 10, 'cl'),
      I('Grenadine', 1.5, 'cl', { note: 'langzaam laten zakken' }),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Vul een longdrinkglas met ijs.',
      'Schenk tequila en sinaasappelsap erin.',
      'Laat de grenadine langzaam langs de rand zakken.',
      'Niet roeren — garneer met sinaasappel en kers.',
    ],
  },
  {
    name: 'Americano',
    description: 'De lichtere voorloper van de Negroni, met bruis.',
    glass: 'highball',
    method: 'build',
    difficulty: 'easy',
    garnish: 'Schijfje sinaasappel',
    tags: ['bitter', 'aperitief', 'bubbels'],
    ingredients: [
      I('Campari', 3, 'cl'),
      I('Rode vermout', 3, 'cl'),
      I('Sodawater', 8, 'cl'),
      I('IJs', 6, 'cube'),
    ],
    instructions: [
      'Vul een glas met ijs.',
      'Schenk Campari en rode vermout erin.',
      'Top af met sodawater.',
      'Garneer met een schijfje sinaasappel.',
    ],
  },
  {
    name: 'Gimlet',
    description: 'Strak en fris: gin met limoen en een vleugje zoet.',
    glass: 'coupe',
    method: 'shaken',
    difficulty: 'easy',
    garnish: 'Schijfje limoen',
    tags: ['citrus', 'fris', 'klassiek'],
    ingredients: [
      I('Gin', 6, 'cl'),
      I('Limoensap', 2, 'cl'),
      I('Suikersiroop', 1.5, 'cl'),
      I('IJs', 5, 'cube'),
    ],
    instructions: [
      'Shake gin, limoensap en siroop met ijs.',
      'Dubbel zeven in een gekoelde coupe.',
      'Garneer met een schijfje limoen.',
    ],
  },
  {
    name: 'Bramble',
    description: 'Gin-sour met een mooie sliert cassis door het ijs.',
    glass: 'rocks',
    method: 'build',
    difficulty: 'medium',
    garnish: 'Citroen en verse bessen',
    tags: ['fruitig', 'citrus', 'modern'],
    ingredients: [
      I('Gin', 5, 'cl'),
      I('Citroensap', 2.5, 'cl'),
      I('Suikersiroop', 1.5, 'cl'),
      I('Crème de cassis', 1.5, 'cl', { note: 'erover druppelen' }),
      I('IJs', 8, 'cube'),
    ],
    instructions: [
      'Schud gin, citroensap en siroop met ijs.',
      'Schenk ongezeefd in een glas met gemalen ijs.',
      'Druppel de crème de cassis erover voor het marmereffect.',
      'Garneer met citroen en verse bessen.',
    ],
  },
];
