import { Component, computed, inject, input } from '@angular/core';
import { DomSanitizer, type SafeHtml } from '@angular/platform-browser';
import { barkastIngredientSVG } from './ingredient-svg';

/**
 * A small hand-drawn ingredient glyph (bottle, citrus, herb, ice…). Picks a shape and colour
 * from the ingredient id + category. The SVG is generated by our own code, so it is trusted.
 */
@Component({
  selector: 'app-ingredient-glyph',
  template: `<span class="wrap" [innerHTML]="html()"></span>`,
  styles: `
    :host {
      display: block;
      width: 100%;
      height: 100%;
    }
    .wrap {
      display: block;
      width: 100%;
      height: 100%;
    }
  `,
})
export class IngredientGlyph {
  private readonly sanitizer = inject(DomSanitizer);
  readonly ingId = input<string | undefined>(undefined);
  readonly cat = input<string | undefined>(undefined);

  protected readonly html = computed<SafeHtml>(() =>
    this.sanitizer.bypassSecurityTrustHtml(barkastIngredientSVG({ id: this.ingId(), cat: this.cat() })),
  );
}
